name = "Tar"
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
authors = ["Stefan Karpinski <stefan@karpinski.org>"]
version = "1.10.0"

[deps]
ArgTools = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
ArgTools = "1.1"
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleBufferStream = "777ac1f9-54b0-4bf8-805c-2214025038e7"
Tar_jll = "9b64493d-8859-5bf3-93d7-7c32dd38186f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "SimpleBufferStream", "Tar_jll", "Test"]
